---
- name: Restart Apache Redhat
  service: name=httpd state=restarted
  when: ansible_os_family == "Redhat"

- name: Restart Apache Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
